name: lint-and-format
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  lint-and-format:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: latest
      - name: install-sponge
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
      - name: biome-backend
        run: |
          cd backend
          pnpm install --frozen-lockfile
          pnpm biome lint --write
          pnpm biome format --write
      - name: biome-frontend
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          pnpm biome lint --write
          pnpm biome format --write
          pnpm formatjs compile-folder src/locale/src src/locale/lang
          pnpm vitest
          ./src/locale/scripts/locale-sort.sh
      - name: nginxbeautifier
        run: |
          pnpm add -g nginxbeautifier
          nginxbeautifier -s 2 -r rootfs/usr/local/nginx/conf
      - name: push changes
        run: |
          git add -A
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git commit -sm "update and lint" || true
          git push || true
